apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: rode
      context: ./
deploy:
  helm:
    releases:
      - name: rode
        chartPath: rode/rode
        version: 0.1.2
        remote: true
        wait: true
        artifactOverrides:
          image: rode
        imageStrategy:
          helm: {}
    flags:
      install: [ "--timeout=10m" ]
profiles:
  - name: local
    activation:
      - kubeContext: docker-for-desktop
      - kubeContext: docker-desktop
    portForward:
    - resourceType: service
      resourceName: rode
      namespace: default 
      port: 50051
      localPort: 50051
    - resourceType: service
      resourceName: rode
      namespace: default
      port: 50052
      localPort: 50052
    - resourceType: service
      resourceName: grafeas-server
      namespace: default 
      port: 8080
      localPort: 8080
    patches:
      - op: add
        path: /deploy/helm/releases/0/namespace
        value: default
      - op: add
        path: /deploy/helm/releases/0/overrides
        value: 
          debug: true
          grafeas-elasticsearch:
            grafeas:
              elasticsearch:
                username: "test1234"
                password: "test1234"
            elasticsearch:
              antiAffinity: "soft"
              esJavaOpts: "-Xmx128m -Xms128m"
              resources:
                requests:
                  cpu: "100m"
                  memory: "512M"
                limits:
                  cpu: "1000m"
                  memory: "512M"
              volumeClaimTemplate:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10M
      - op: add
        path: /build/artifacts/1
        value:
          image: grpc-swagger
          context: ./tools/grpc-swagger
      - op: add
        path: /deploy/helm/releases/1
        value:
          name: grpc-swagger
          chartPath: tools/grpc-swagger/chart
          artifactOverrides:
            image.name: grpc-swagger
  - name: demo
    patches:
      - op: add
        path: /deploy/helm/releases/0/namespace
        value: rode-demo
      - op: add
        path: /deploy/helm/releases/0/overrides
        value: 
          grafeas:
            enabled: false
          grafeasHost: "grafeas-server.rode-demo-grafeas.svc.cluster.local:8080"
          opaHost: "rode-opa.rode-demo.svc.cluster.local:8181"
          debug: true
