apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: rode
      context: ./
deploy:
  helm:
    releases:
      - name: rode
        chartPath: helm/rode
        skipBuildDependencies: true
        wait: true
        artifactOverrides:
          image: rode
        imageStrategy:
          helm: {}
profiles:
  - name: local
    activation:
      - kubeContext: docker-for-desktop
      - kubeContext: docker-desktop
    patches:
      - op: add
        path: /deploy/helm/releases/0/namespace
        value: default
      - op: add
        path: /deploy/helm/releases/0/overrides
        value: 
          debug: true
      - op: add
        path: /build/artifacts/1
        value:
          image: grpc-swagger
          context: ./tools/grpc-swagger
      - op: add
        path: /deploy/helm/releases/1
        value:
          name: grpc-swagger
          chartPath: tools/grpc-swagger/chart
          artifactOverrides:
            image.name: grpc-swagger
